#!/usr/bin/env python

from optparse import OptionParser

from adolphus import Experiment, parse_experiment


if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option("-c", "--conf", dest="conf", default=None, 
        help="custom configuration file to load")
    parser.add_option("-i", "--inactive", dest="active", default=True,
        action="store_false", help="cameras are inactive by default")

    (options, args) = parser.parse_args()

    model, relevances = parse_experiment(args[0])
    Experiment(model, relevance_models=relevances, config_file=options.conf).run()
