#!/usr/bin/env python

from optparse import OptionParser

from adolphus import Experiment, parse_experiment


def main():
    parser = OptionParser()
    parser.add_option("-c", "--conf", dest="conf", default=None, 
        help="custom configuration file to load")
    parser.add_option("-i", "--inactive", dest="active", default=True,
        action="store_false", help="cameras are inactive by default")
    parser.add_option("-z", "--zoom", dest="zoom", default=False,
        action="store_true", help="disable camera view and use visual zoom")

    (options, args) = parser.parse_args()

    model, relevances = parse_experiment(args[0], active=options.active)
    Experiment(model, relevance_models=relevances, config_file=options.conf,
               zoom=options.zoom).run()


if __name__ == '__main__':
    main()
